export const AGREEMENT_STATUSES = [
  "DRAFT",
  "INVITED",
  "AWAITING_FUNDING",
  "FUNDED_AWAITING_ACCEPTANCE",
  "ACCEPTED",
  "IN_PROGRESS",
  "COMPLETED",
  "DECLINED",
  "EXPIRED",
  "CANCELLATION_PENDING",
  "CANCELLED",
  "DISPUTED",
  "SECURITY_HOLD",
  "REFUND_PENDING",
  "REFUNDED",
  "FAILED",
] as const;

export type AgreementStatus = (typeof AGREEMENT_STATUSES)[number];

export const allowedAgreementTransitions: Record<AgreementStatus, readonly AgreementStatus[]> = {
  DRAFT: ["INVITED", "CANCELLED"],
  INVITED: ["AWAITING_FUNDING", "CANCELLED"],
  AWAITING_FUNDING: ["FUNDED_AWAITING_ACCEPTANCE", "FAILED", "CANCELLED"],
  FUNDED_AWAITING_ACCEPTANCE: ["ACCEPTED", "DECLINED", "EXPIRED", "REFUND_PENDING"],
  ACCEPTED: ["IN_PROGRESS", "CANCELLATION_PENDING", "DISPUTED"],
  IN_PROGRESS: ["COMPLETED", "CANCELLATION_PENDING", "DISPUTED", "SECURITY_HOLD"],
  COMPLETED: [],
  DECLINED: ["REFUND_PENDING"],
  EXPIRED: ["REFUND_PENDING"],
  CANCELLATION_PENDING: ["CANCELLED", "REFUND_PENDING", "IN_PROGRESS"],
  CANCELLED: [],
  DISPUTED: ["IN_PROGRESS", "REFUND_PENDING", "COMPLETED", "SECURITY_HOLD"],
  SECURITY_HOLD: ["IN_PROGRESS", "REFUND_PENDING", "COMPLETED"],
  REFUND_PENDING: ["REFUNDED", "FAILED"],
  REFUNDED: [],
  FAILED: ["AWAITING_FUNDING", "IN_PROGRESS", "REFUND_PENDING"],
};

export const canTransitionAgreement = (from: AgreementStatus, to: AgreementStatus) =>
  allowedAgreementTransitions[from].includes(to);
