import type { JobSummary } from "@veyrivo/domain";

export const jobs: JobSummary[] = [
  {
    id: "VY-1048",
    title: "Checkout experience redesign",
    counterparty: "Northstar Labs",
    role: "WORKER",
    status: "IN_PROGRESS",
    displayStatus: "UNDER_REVIEW",
    asset: "CKB",
    total: 184000,
    released: 92000,
    milestoneProgress: "2 of 3",
    nextAction: "Client review due in 2 days",
    updatedAt: "18 min ago",
  },
  {
    id: "VY-1046",
    title: "Brand launch photography",
    counterparty: "Mira Okafor",
    role: "CLIENT",
    status: "FUNDED_AWAITING_ACCEPTANCE",
    displayStatus: "FUNDED_AWAITING_ACCEPTANCE",
    asset: "CKB",
    total: 76000,
    released: 0,
    milestoneProgress: "0 of 2",
    nextAction: "Waiting for worker acceptance",
    updatedAt: "3 hours ago",
  },
  {
    id: "VY-1039",
    title: "July content production",
    counterparty: "Kora Studio",
    role: "CLIENT",
    status: "IN_PROGRESS",
    displayStatus: "IN_PROGRESS",
    asset: "CKB",
    total: 112500,
    released: 37500,
    milestoneProgress: "1 of 3",
    nextAction: "Milestone due 28 Jul",
    updatedAt: "Yesterday",
  },
];

export const jobDetails = {
  "VY-1048": {
    summary: jobs[0],
    description:
      "Redesign the mobile and desktop checkout journey, improve payment clarity, and deliver an implementation-ready Figma prototype.",
    createdAt: "08 July 2026",
    fundedAt: "09 July 2026",
    payoutAddress: "ckb1qyq...w7m2k9",
    milestones: [
      {
        title: "User-flow audit",
        status: "RELEASED",
        amount: 46000,
        due: "12 Jul",
        evidence: "Audit report and annotated flow",
        note: "Released 13 July",
      },
      {
        title: "High-fidelity checkout",
        status: "UNDER_REVIEW",
        amount: 92000,
        due: "23 Jul",
        evidence: "Figma prototype and design notes",
        note: "Proof submitted 18 minutes ago",
      },
      {
        title: "Developer handoff",
        status: "PENDING",
        amount: 46000,
        due: "30 Jul",
        evidence: "Component specs and exported assets",
        note: "Starts after milestone 2",
      },
    ],
  },
  "VY-1046": {
    summary: jobs[1],
    description:
      "Produce a cohesive set of launch photographs for the new Kora home collection, including web and social crops.",
    createdAt: "20 July 2026",
    fundedAt: "23 July 2026",
    payoutAddress: "Pending worker acceptance",
    milestones: [
      {
        title: "Creative direction and shot list",
        status: "PENDING",
        amount: 18000,
        due: "29 Jul",
        evidence: "Approved moodboard and shot list",
        note: "Waiting for worker acceptance",
      },
      {
        title: "Final edited photographs",
        status: "PENDING",
        amount: 58000,
        due: "08 Aug",
        evidence: "24 edited originals and web crops",
        note: "Not started",
      },
    ],
  },
  "VY-1039": {
    summary: jobs[2],
    description:
      "Create twelve editorial posts and accompanying visual assets for the July product education campaign.",
    createdAt: "25 June 2026",
    fundedAt: "27 June 2026",
    payoutAddress: "ckb1qyq...3p8n4d",
    milestones: [
      {
        title: "Content plan",
        status: "RELEASED",
        amount: 37500,
        due: "04 Jul",
        evidence: "Calendar and approved briefs",
        note: "Released 05 July",
      },
      {
        title: "First six articles",
        status: "ACTIVE",
        amount: 37500,
        due: "28 Jul",
        evidence: "Six document links and image folder",
        note: "Work in progress",
      },
      {
        title: "Final six articles",
        status: "PENDING",
        amount: 37500,
        due: "12 Aug",
        evidence: "Six document links and image folder",
        note: "Not started",
      },
    ],
  },
} as const;
